### ISSUE TITLE
Error install from Symfony Installer

### ISSUE THREAD

**Issue by ihsanudin** [symfony/symfony-standard#896] opened 2015-12-01 07:47 UTC
```
PHP Warning:  require(/home/aden/Playground/Skeleton/app/SymfonyRequirements.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/symfony:0
PHP   2. require() /usr/local/bin/symfony:10
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:35
PHP   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Application.php:878
PHP   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Command/Command.php:259
PHP   8. Symfony\Installer\DownloadCommand->checkSymfonyRequirements() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:65
PHP Fatal error:  require(): Failed opening required '/home/aden/Playground/Skeleton/app/SymfonyRequirements.php' (include_path='.:/usr/share/php:/usr/share/pear') in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/symfony:0
PHP   2. require() /usr/local/bin/symfony:10
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:35
PHP   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Application.php:878
PHP   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Command/Command.php:259
PHP   8. Symfony\Installer\DownloadCommand->checkSymfonyRequirements() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:65
```

**Comment by javiereguiluz** [comment] 2015-12-01 07:50
@ihsanudin thanks for reporting this error.

The good news is that the problem is already solve in the most recent installer version.

The bad news is that we have a problem updating the installer to the latest version (we are talking about that in [this discussion](https://github.com/symfony/symfony-installer/issues/212)).

The solution that would work right now is to reinstall the symfony installer. It will only take a minute. Thanks!

**Comment by ihsanudin** [comment] 2015-12-01 08:04
@javiereguiluz : thanks for information :-) :+1:

**Comment by Tobion** [comment] 2015-12-02 21:29
Closing as this is about symfony-installer and is fixed there.

**Closed by Tobion** 2015-12-02 21:29 UTC
