### ISSUE TITLE
Bundle generation using generate:bundle command does not work

### ISSUE THREAD

**Issue by leettastic** [symfony/symfony-standard#1098] opened 2017-07-04 09:46 UTC
```
$ php bin/console generate:bundle

                                            
  Welcome to the Symfony bundle generator!  
                                            

Are you planning on sharing this bundle across multiple applications? [no]: 

Your application code must be written in bundles. This command helps
you generate them easily.

Give your bundle a descriptive name, like BlogBundle.
Bundle name: BlogBundle

Bundles are usually generated into the src/ directory. Unless you're
doing something custom, hit enter to keep this default!

Target Directory [src/]: 

What format do you want to use for your generated configuration?

Configuration format (annotation, yml, xml, php) [annotation]: 

                     
  Bundle generation  
                     

> Generating a sample bundle skeleton into app/../src/BlogBundle
  created ./app/../src/BlogBundle/
  created ./app/../src/BlogBundle/BlogBundle.php
  created ./app/../src/BlogBundle/Controller/
  created ./app/../src/BlogBundle/Controller/DefaultController.php
  created ./app/../tests/BlogBundle/Controller/
  created ./app/../tests/BlogBundle/Controller/DefaultControllerTest.php
  created ./app/../src/BlogBundle/Resources/views/Default/
  created ./app/../src/BlogBundle/Resources/views/Default/index.html.twig
  created ./app/../src/BlogBundle/Resources/config/
  created ./app/../src/BlogBundle/Resources/config/services.yml
> Checking that the bundle is autoloaded
> Enabling the bundle inside app/AppKernel.php
  updated ./app/AppKernel.php
> Importing the bundle's routes from the app/config/routing.yml file
  updated ./app/config/routing.yml
> Importing the bundle's services.yml from the app/config/config.yml file
  updated ./app/config/config.yml

                                         
  Everything is OK! Now get to work :).  
```

```
$ php bin/console

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "BlogBundle" from namespace "BlogBundle".
Did you forget a "use" statement for another namespace? in /var/www/vagrant/app/AppKernel.php:19

Stack trace:
#0 /var/www/vagrant/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#1 /var/www/vagrant/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(137): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#4 /var/www/vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(90): Symfony\Bundle\FrameworkBundle\Console\Application->add(Object(Symfony\Component\Con in /var/www/vagrant/app/AppKernel.php on line 19
```

**Comment by speadup** [comment] 2017-07-04 10:08
Same to me. See #1097

**Comment by leettastic** [comment] 2017-07-04 10:14
Works fine with version 3.1 but not in versions 3.2, 3.3, 3.4

**Comment by speadup** [comment] 2017-07-04 10:32
Tag v3.3.2 works fine too.

**Comment by leettastic** [comment] 2017-07-04 12:18
You need to make change in composer.json, change

```
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
```

to

```
        "psr-4": { "": "src/" },
```

This solved the issue for me

**Comment by speadup** [comment] 2017-07-04 12:23
Well,maybe add bundle namespace to psr4 is better. Let me try.

**Comment by speadup** [comment] 2017-07-04 14:30
I change
> 
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
to

        "psr-4": {
            "AppBundle\\": "src/AppBundle",
            "AdminBundle\\": "src/AdminBundle"
        },

works fine. I believe that this can get better performance.

**Comment by Ximo14** [comment] 2017-07-04 16:19
Any solution?

**Comment by joaquingch** [comment] 2017-07-04 16:28
Any solution?

**Comment by Pierstoval** [comment] 2017-07-04 16:45
I'm not sure the generator should change the contents of the `composer.json` file.

But something that can be done is that the generator may check whether the file exists when autoloaded, if not, add a warning that the file is not covered by `psr-4` rules.

WDYT?

**Comment by Tobion** [comment] 2017-07-05 22:23
Considering symfonfy flex does this command have any future at all? I doubt it.

**Comment by HeahDude** [comment] 2017-07-06 11:53
Having the kernel in `src/` should not prevent having bundles too especially when you need to override one, what would be the reason to stop supporting it?

**Comment by Pierstoval** [comment] 2017-07-06 15:41
Even though the recommendation is to have bundleless apps, Symfony still needs bundles to decouple some features into separate packages.

Therefore, having bundles is something that should be supported in any way. Especially when the command is able to generate boilerplate code needed in most third-party bundles.

**Comment by patrickbussmann** [comment] 2017-07-08 12:36
I found the problem 😆 
https://github.com/symfony/symfony-standard/pull/1048

But I don't understand why there is a pull request which brokes a command which the most users use @Pierstoval.
I mean okay, specify the namespaces looks great and everything but its like with NPM or Composer itself. If symfony users using `php bin/console generate:bundle` and after that everything is broken that is stupid. 😢 
The `composer` commands modify the `composer.json` so that the bundle can do this, too. Why not. If everything is working well then 😄 

So I think either it will be reverted or we update the generator bundle, too.

**Comment by xabbuh** [comment] 2017-07-08 17:17
I wonder if this shouldn't be reported in the SensioGeneratorBundle repository instead. IMO the bundle could easily make sure that the autoloader is updated or report a message if the `composer.json` file could not be manipulated/found.

**Comment by Pierstoval** [comment] 2017-07-10 19:38
The #1048 PR was made to optimize autoloading, because having an empty namespace pointing to a directory has an impact on autoloading performances. Even though it's not documented, I think it's useful to get benefit from this small upgrade.

That certainly is the reason why in Flex the original namespace is `App` pointing to `src/`: autoloading performances, but I'm not sure.

**Comment by guilliamxavier** [comment] 2017-07-12 14:16
There are two different problems, both reported on https://github.com/sensiolabs/SensioGeneratorBundle/issues/555 and https://github.com/sensiolabs/SensioGeneratorBundle/issues/558

**Comment by dunglas** [comment] 2017-07-17 22:16
Maybe should we just revert https://github.com/symfony/symfony-standard/pull/1048 while SensioGeneratorBundle isn't fixed? It looks like it creates a lot of problem for newcomers https://stackoverflow.com/questions/45151067/class-not-found-exception-in-appkernel-after-moving-to-symfony2-8-24#comment77274270_45151067

**Comment by Bubelbub** [comment] 2017-07-17 22:27
@dunglas I think the newcomers will read the documentation and know that they must add the bundle. https://symfony.com/doc/current/bundles/SensioGeneratorBundle/commands/generate_bundle.html

The problem is that "old" developers like I know the way it was with symfony2 and try to use it like it was.
So at the end nobody reads the documentation all the time they develope.
Like the certificated specialists who wondering that this way changed 😄

**Comment by dunglas** [comment] 2017-07-17 22:34
A lot of material still exist and don't use new best practices, and nobody will read this documentation :)
The generator should at least display a message pointing to this doc, or asking the user to copy a line in `composer.json`.

**Comment by fabpot** [comment] 2017-07-18 06:59
@dunglas This has been fixed some days ago. We did 2 things: first, we fixed the error message that was not displayed anymore when the generator was not able to register the bundle. Then, we added some docs about the issue.

**Comment by fabpot** [comment] 2017-07-18 07:00
That being said, we can also revert the change here if that helps. That does not make a big difference anyway.

**Comment by xabbuh** [comment] 2017-07-18 07:47
In https://github.com/symfony/symfony-standard/issues/1098#issuecomment-313868965 I suggested that the SensioGeneratorBundle could try to update the `autoload` section in the `composer.json` file. Would that be an option in addition to the error reporting changes that have been made?

**Comment by fabpot** [comment] 2017-07-18 07:55
@xabbuh Indeed, that would be even better!

**Comment by paullandre** [comment] 2018-01-09 08:59
This still occurs in Symfony 2.7 upon creating a Bundle

**Comment by fabpot** [comment] 2018-01-10 07:05
Closing this old ticket, much has changed since then.

**Closed by fabpot** 2018-01-10 07:05 UTC
