### ISSUE TITLE
Unable to escape '%' character in configuration files

### ISSUE THREAD

**Issue by freyr** [symfony/symfony-standard#1084] opened 2017-06-01 10:42 UTC
I'm not sure, but this looks like a bug:

Fresh installation of Symfony Standard (using symfony installer), I've changed db password in `app/config/parameters.yml` to contain two '%' chars, that there was couple of characters between them (like "some%pass%word"). At the end I've executed : `php bin/console server:start`

Effect:

`PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message '`You have requested a non-existent parameter "pass".`

It looks like single and double quoting of strings in configurations doesn't work on '%' chars, when string could be recognized as a variable - even if '%' chars  are not at the beginning or end of a string. 

Question: this is a bug or a feature?

**Comment by stof** [comment] 2017-06-01 10:47
In the container, percent signs must be escaped by doubling them.

this is totally separate from YAML escaping (it is not about escaping at the YAML level, but at the container level)

**Comment by xabbuh** [comment] 2017-06-02 13:22
closing here as this is indeed not a bug like @stof explained

**Closed by xabbuh** 2017-06-02 13:22 UTC
