### ISSUE TITLE
Need to warmup production cache for app_dev

### ISSUE THREAD

**Issue by mark-netants** [symfony/symfony-standard#1053] opened 2017-03-03 22:14 UTC
Sinds the update to 3.2 i needed to run cache:warmup --env=prod even when running the application in development mode.
If this was not done the application would not function correctly because its using the doctrine proxies from prod in this cache folder.

By running cache:warmup --env=prod my app was able to run without any problems.

**Comment by Pierstoval** [comment] 2017-03-04 07:36
Environment are not tied together, I don't understand why warming up the prod env could have an impact on dev, because the difference is made at the very beginning of the code, in the console or in the front controller 😕 

I feel like there is an issue somewhere 😕

**Comment by fabpot** [comment] 2017-05-01 17:51
Closing as it looks like a problem not related to Symfony. Feel free to reopen with more details about how to reproduce this issue.

**Closed by fabpot** 2017-05-01 17:51 UTC
