### ISSUE TITLE
composer.json is Empty after instalation of Symfony

### ISSUE THREAD

**Issue by sinner** [symfony/symfony-standard#876] opened 2015-10-24 15:06 UTC
composer.json file is empty after instalation of Symfony Standar Edition 2.7.

**Comment by ogizanagi** [comment] 2015-10-24 15:09
How did you install the Symfony Standard Edition ?

**Comment by sinner** [comment] 2015-10-24 15:12
I run on the terminal:

```sh
symfony new proyectName
```

**Comment by ogizanagi** [comment] 2015-10-24 15:17
I cannot reproduce the issue with both 1.1.7 version and last (1.3) version of the installer.
Which version of the installer do you use ?
Anyway, it seems to be a `symfony-installer` issue. So it should be opened [on this repository](https://github.com/symfony/symfony-installer/issues) if confirmed.

**Comment by sinner** [comment] 2015-10-24 15:23
Yes is weird... The version I used was 1.1.7

**Comment by Tobion** [comment] 2015-10-24 15:27
Closing for the reasons provided by @ogizanagi

**Closed by Tobion** 2015-10-24 15:27 UTC
